#!/usr/bin/env python3
# Copyright (c) 2026 The xCoin developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
'''
Generate the XIP-4 (HX1) handshake test vectors in src/test/data/hx1_handshake_vectors.json.

The handshakes run between two copies of the test framework's EncryptedP2PState
(test/functional/test_framework/v2_p2p.py), and every field is then recomputed
from the recorded bytes with hmac, hashlib and the framework's ML-KEM-768
(test_framework/crypto/mlkem.py) and checked. This script also recomputes the
two ElligatorSwift keys from their secret keys and aux entropy, the way
libsecp256k1's secp256k1_ellswift_create does, and checks them against the
pinned values.

The output is deterministic. XIP-4 lists the same values, generated by a
separate program; test/functional/test_framework/v2_p2p.py checks a subset.
'''

import hashlib
import json
import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '../../test/functional'))

from test_framework.crypto import mlkem  # noqa: E402
from test_framework.crypto.bip324_cipher import HX1_KIND_OFFER, hx1_encode_record  # noqa: E402
from test_framework.crypto.ellswift import xswiftec, xswiftec_inv  # noqa: E402
from test_framework.crypto.secp256k1 import FE, G  # noqa: E402
from test_framework.v2_p2p import (  # noqa: E402
    HX1_MODE_OFF,
    HX1_VECTOR_APP_PACKETS,
    HX1_VECTOR_INPUTS,
    HX1_VECTOR_PINNED_APP_PACKETS,
    hx1_bad_encapsulation_keys,
    hx1_handshake_vector,
)


def ellswift_create_libsecp256k1(seckey32, auxrnd32):
    """secp256k1_ellswift_create (src/secp256k1/src/modules/ellswift/main_impl.h): a deterministic
    ElligatorSwift encoding of seckey*G, drawn from SHA256-based randomness keyed by seckey and auxrnd32."""
    tag = hashlib.sha256(b"secp256k1_ellswift_create").digest()
    hasher = hashlib.sha256(tag + tag + seckey32 + bytes(32) + auxrnd32)

    def prng(cnt):
        h = hasher.copy()
        h.update(cnt.to_bytes(4, 'little'))
        return h.digest()

    p = int.from_bytes(seckey32, 'big') * G
    cnt = 0
    branches_left = 0
    while True:
        if branches_left == 0:
            branch_hash = prng(cnt)
            cnt += 1
            branches_left = 64
        branches_left -= 1
        branch = (branch_hash[branches_left >> 1] >> ((branches_left & 1) << 2)) & 7
        u32 = prng(cnt)
        cnt += 1
        u = FE(int.from_bytes(u32, 'big'))
        t = xswiftec_inv(p.x, u, branch)
        if t is not None:
            break
    if t.is_even() != p.y.is_even():
        t = -t
    assert xswiftec(u, t) == p.x
    return u32 + t.to_bytes()


def main():
    inp = HX1_VECTOR_INPUTS
    for side in ("I", "R"):
        assert ellswift_create_libsecp256k1(inp[f"priv_{side}"], inp[f"aux_{side}"]) == inp[f"ell_{side}"]

    ek, dk = mlkem.keygen_internal(inp["d"], inp["z"])
    kem_secret, ct = mlkem.encaps_internal(ek, inp["m"])
    flipped = bytes([ct[0] ^ 1]) + ct[1:]
    rejection = mlkem.decaps_internal(dk, flipped)
    assert rejection == mlkem.J(inp["z"] + flipped) and rejection != kem_secret
    bad1, bad2 = hx1_bad_encapsulation_keys(ek)
    assert mlkem.check_encaps_key(ek) and not mlkem.check_encaps_key(bad1) and not mlkem.check_encaps_key(bad2)

    handshakes = [
        hx1_handshake_vector("V1", "mainnet"),
        hx1_handshake_vector("V2", "testnet"),
        hx1_handshake_vector("V3", "regtest"),
        hx1_handshake_vector("V4", "mainnet", responder_decoys=[bytes.fromhex("dec001")],
                             initiator_decoys=[b"", bytes.fromhex("dec0020304")],
                             initiator_decoys_after_switch=[bytes.fromhex("dec005")]),
        hx1_handshake_vector("V5", "mainnet", responder_mode=HX1_MODE_OFF),
    ]
    descriptions = {
        "V1": "mainnet, both sides in prefer mode, no decoys other than the responder's confirmation packet (its first "
              "stage-2 packet, a decoy with empty contents sent right after it switches to stage 2)",
        "V2": "testnet A, same inputs as V1",
        "V3": "regtest, same inputs as V1",
        "V4": "mainnet, same inputs as V1, with decoys: the responder sends one before VP_R (it carries garbage_R as "
              "associated data); the initiator sends two before VP_I (the first carries garbage_I) and one stage-2 decoy "
              "right after VP_I",
        "V5": "mainnet, a prefer-mode initiator meets a classical (mode 0) responder: both version packets are empty and "
              "the session stays on the stage-1 keys",
    }
    for h in handshakes:
        h["description"] = descriptions[h["name"]]

    vectors = {
        "source": "XIP-4 (HX1) handshake vectors, generated by contrib/testgen/gen_hx1_handshake_vectors.py from the "
                  "test framework (test/functional/test_framework/v2_p2p.py). Each input is SHA-256 of 'XIP-4 test "
                  "vector: ' followed by its name (garbage truncated); ell_initiator and ell_responder are "
                  "secp256k1_ellswift_create(priv, aux). Application packet i has the contents 'I->R' or 'R->I' "
                  f"followed by i as 4 bytes little-endian; {HX1_VECTOR_APP_PACKETS} are sent each way, and entries "
                  f"pin application packets {', '.join(map(str, HX1_VECTOR_PINNED_APP_PACKETS))} plus every decoy. "
                  "In a hybrid session the responder's stage-2 stream starts with its confirmation packet (stage-2 "
                  "index 0, a decoy with empty contents), so its application packet i has stage-2 index i + 1. "
                  "All sha256 fields are SHA-256.",
        "inputs": {
            "priv_initiator": inp["priv_I"].hex(), "aux_initiator": inp["aux_I"].hex(),
            "priv_responder": inp["priv_R"].hex(), "aux_responder": inp["aux_R"].hex(),
            "garbage_initiator": inp["garbage_I"].hex(), "garbage_responder": inp["garbage_R"].hex(),
            "mlkem_d": inp["d"].hex(), "mlkem_z": inp["z"].hex(), "mlkem_m": inp["m"].hex(),
            "ell_initiator": inp["ell_I"].hex(), "ell_responder": inp["ell_R"].hex(),
        },
        "mlkem768": {
            "description": "FIPS 203 KeyGen_internal(d, z) and Encaps_internal(ek, m) for the inputs above, and Decaps of "
                           "ct with bit 0 of byte 0 flipped (implicit rejection, J(z || ct'))",
            "ek_sha256": hashlib.sha256(ek).hexdigest(), "dk_sha256": hashlib.sha256(dk).hexdigest(),
            "ct_sha256": hashlib.sha256(ct).hexdigest(), "shared_secret": kem_secret.hex(),
            "decaps_flipped_ct": rejection.hex(),
            "offer_record_sha256": hashlib.sha256(hx1_encode_record(HX1_KIND_OFFER, ek)).hexdigest(),
        },
        "handshakes": handshakes,
        "bad_encapsulation_keys": {
            "description": "V6: V1's ek with one coefficient out of range; an initiator that receives either in an "
                           "otherwise valid OFFER must disconnect without sending VP_I",
            "keys": [
                {"name": "bad1", "change": "first 12-bit coefficient set to 3329", "ek": bad1.hex(),
                 "sha256": hashlib.sha256(bad1).hexdigest()},
                {"name": "bad2", "change": "last coefficient of the third polynomial set to 4095", "ek": bad2.hex(),
                 "sha256": hashlib.sha256(bad2).hexdigest()},
            ],
        },
    }
    json.dump(vectors, sys.stdout, indent=1)
    sys.stdout.write("\n")


if __name__ == '__main__':
    main()
